### ISSUE TITLE
How to integrate product with aws-amplify

### ISSUE THREAD

**Issue by paragbaxi** [creativetimofficial/ct-nextjs-material-dashboard-pro#1]
### Version
1.0.0
### Reproduction link
https://jsfiddle.net/paragbaxi/x16rce70/1/
### Operating System
Mac
### Device
Apple
### Browser & Version
86.0.4240.111
### Steps to reproduce
yarn add @aws-amplify
add withAuthenticator to exported page
### What is expected?
after passing authenticator HOC, layout sidebar shows
### What is actually happening?
`Dashboard.layout = Admin` does not work

---

**Comment by einazare** [comment]
Hello there, @paragbaxi ,

I've read the docs of aws-amplify and I see the following:
```
import React from 'react';
import { withAuthenticator, AmplifySignOut } from '@aws-amplify/ui-react';

const App = () => (
  <div>
    <AmplifySignOut />
    My App
  </div>
);

export default withAuthenticator(App);
```
So my best guess you have something the same.
Please try the following:
```
import React from 'react';
import { withAuthenticator, AmplifySignOut } from '@aws-amplify/ui-react';
....

function Dashboard() {
  ...
};

let withAuthenticatorDashboard = withAuthenticator(Dashboard);
withAuthenticatorDashboard.layout = Admin;

export default withAuthenticatorDashboard;
```

Best,
Manu

**Comment by paragbaxi** [comment]
Worked!
