### ISSUE TITLE
[Bug] Too many depreciated modules

### ISSUE THREAD

**Issue by ideaztech** [creativetimofficial/ct-nextjs-material-dashboard-pro#16]
### Version
1.1.0
### Reproduction link
https://mckee-web-app-1kyjiv40r-ideaztechnologies.vercel.app/admin/widgets
### Operating System
 Windows 10
### Device
PC
### Browser & Version
Chrome
### Steps to reproduce
It was very hard to get the exact correct combination of module versions to get this to work.  Many of the modules used are depreciated, such as @zeit/next-sass,  @zeit/next-css, and node-sass.  Also, react-big-calendar and react-datetime have conflicts with the  other modules.  The only way to avoid the conflicts is to install older versions.  
### What is expected?
We hoped this project would be a great system for years to come!
### What is actually happening?
It is already out-dated and depreciated before we even started using it.

---

**Comment by tom-mcvay** [comment]
Are there any updates for this? The packages are a huge mess, struggling to find versions to get it to run with all the deprecated packages

**Comment by sajadevo** [comment]
**Hi there**

We've updated the product to v2 and now it has a totally new and fresh design with a reusable, flexible and scalable base structure and all of the issues are fixed on the new update of the product.

**Note: To get the latest updates and supports for the products and other related things to Creative Tim please join our [Discord Community](https://discord.gg/7xzMRsRebr).**

**All the best,
Sajad 
React Developer @ [Creative-Tim.com](http://creative-tim.com/)**
