### ISSUE TITLE
Deprecated dependencies for nextjs-material-dashboard-pro

### ISSUE THREAD

**Issue by more-dinner** [creativetimofficial/ct-nextjs-material-dashboard-pro#17]
### Version
nextjs-material-dashboard-pro-v1.1.0
### Reproduction link
https://www.creative-tim.com/learning-lab/nextjs/quick-start/material-dashboard
### Operating System
MacOS
### Device
Macbook Pro
### Browser & Version
Terminal
### Steps to reproduce
Install NodeJS LTS version from NodeJs Official Page
Go to creative tim website and login into your account
Go to downloads section on creative tim website (be sure to be logged into your account)
Press the download button near NextJS Material Dashboard (FREE or PRO) product (this will download onto your computer a zip file)
Unzip the downloaded file to a folder in your computer
Open Terminal
Go to your file project (where you’ve unzipped the product)
Run in terminal npm install
Then run npm run dev

(These steps are also here https://www.creative-tim.com/learning-lab/nextjs/quick-start/material-dashboard)
### What is expected?
Install without deprecation warnings
### What is actually happening?
kmac:nextjs-service kyleforster$ npm install
npm WARN deprecated @zeit/next-css@1.0.1: Next.js now has built-in support for CSS: https://nextjs.org/docs/basic-features/built-in-css-support. The built-in support solves many bugs and painpoints that the next-css plugin had.
npm WARN deprecated @zeit/next-sass@1.0.1: Next.js now has built-in support for Sass: https://nextjs.org/docs/basic-features/built-in-css-support\#sass-support. The built-in support solves many bugs and painpoints that the next-sass plugin had.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated fsevents@2.1.3: "Please update to latest v2.3 or v2.2"
npm WARN deprecated querystring@0.2.1: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.

and 

npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN react-big-calendar@0.30.0 requires a peer of react@^16.6.1 but none is installed. You must install peer dependencies yourself.
npm WARN react-big-calendar@0.30.0 requires a peer of react-dom@^16.6.1 but none is installed. You must install peer dependencies yourself.
npm WARN react-chartist@0.14.3 requires a peer of react@^0.14.9 || ^15.0.0 || ^16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-datetime@3.0.4 requires a peer of react@^16.5.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-swipeable-views@0.13.9 requires a peer of react@^15.3.0 || ^16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-event-listener@0.6.6 requires a peer of react@^16.3.0 but none is installed. You must install peer dependencies yourself.

and 

found 6 vulnerabilities (5 moderate, 1 high)
  run `npm audit fix` to fix them, or `npm audit` for details

---
### Solution
Your company should your dependencies as per your responsibilities in your support agreement.

**Comment by tom-mcvay** [comment]
Has this issue been resolved? This bug is preventing me from upgrading to the latest Next JS packages

**Comment by SirMauri** [comment]
Leaving a comment to give follow up to this issue. Also having this issue with the project, to many dependency issues to solve.

**Comment by sargitcom** [comment]
I did manage to update package.json, thou template does look off. Images are not loading and menu in sidebar does not look ok. When can we expect to have dependencies and template updated?

**Comment by sajadevo** [comment]
**Hi there**

We've updated the product to v2 and now it has a totally new and fresh design with a reusable, flexible and scalable base structure and all of the issues are fixed on the new update of the product.

**Note: To get the latest updates and supports for the products and other related things to Creative Tim please join our [Discord Community](https://discord.gg/7xzMRsRebr).**

**All the best,
Sajad 
React Developer @ [Creative-Tim.com](http://creative-tim.com/)**
