### ISSUE TITLE
[Feature Request] Update package.json and other files

### ISSUE THREAD

**Issue by sargitcom** [creativetimofficial/ct-nextjs-material-dashboard-pro#19]
### What is your enhancement?
Package.json and files within template must be updated to reflect modern standards. So far, I did manage to upgrade package.json with this:

{
  "name": "nextjs-material-dashboard-pro",
  "version": "1.1.0",
  "private": true,
  "scripts": {
    "start": "next start",
    "build": "next build",
    "dev": "next dev",
    "install:clean": "rm -rf node_modules/ && rm -rf package-lock.json && npm install && npm run dev",
    "compile:scss": "saas assets/scss/nextjs-material-dashboard-pro.scss assets/css/nextjs-material-dashboard-pro.css",
    "minify:scss": "saas assets/scss/nextjs-material-dashboard-pro.scss assets/css/nextjs-material-dashboard-pro.min.css --output-style compressed",
    "map:scss": "saas assets/scss/nextjs-material-dashboard-pro.scss assets/css/nextjs-material-dashboard-pro.css --source-map true",
    "build:scss": "npm run compile:scss && npm run minify:scss && npm run map:scss"
  },
  "dependencies": {
    "@emotion/react": "^11.7.0",
    "@emotion/styled": "^11.6.0",
      "@material-ui/core": "4.11.3",
      "@material-ui/icons": "4.11.2",
    "@material-ui/styles": "^4.11.4",
    "chartist": "0.10.1",
    "classnames": "2.2.6",
    "history": "5.0.0",
    "match-sorter": "6.1.0",
    "moment": "2.29.1",
    "@reduxjs/toolkit": "^1.6.2",
    "luxon": "^2.0.2",
    "next": "11.1.2",
    "react-redux": "^7.2.5",
    "next-compose-plugins": "2.2.1",
    "next-images": "1.8.4",
    "nouislider": "14.6.3",
    "path": "0.12.7",
    "perfect-scrollbar": "1.5.0",
    "react": "17.0.2",
    "react-big-calendar": "0.38.1",
    "react-bootstrap-sweetalert": "5.2.0",
    "react-chartist": "0.14.4",
    "react-datetime": "3.1.1",
    "react-dom": "17.0.2",
    "react-jvectormap": "0.0.16",
    "react-swipeable-views": "0.14.0",
    "react-table": "7.6.3",
    "sass": "*"
  },
  "optionalDependencies": {
    "typescript": "4.1.3"
  }
}

Thou, panel does not look good. Images are missing, menu in the sidebar does not look good. 

Could you update panel with modern dependencies to reflect nowdays state of work.

**Comment by woodward54** [comment]
Did you get it working? tried removing the withSass and withCSS plugins and now Im getting a different error. Im not even able to get the page to load.


Failed to compile
./assets/img/apple-icon.png
TypeError: unsupported file type: undefined (file: undefined)

**Comment by sajadevo** [comment]
**Hi there**

We've updated the product to v2 and now it has a totally new and fresh design with a reusable, flexible and scalable base structure and all of the issues are fixed on the new update of the product.

**Note: To get the latest updates and supports for the products and other related things to Creative Tim please join our [Discord Community](https://discord.gg/7xzMRsRebr).**

**All the best,
Sajad 
React Developer @ [Creative-Tim.com](http://creative-tim.com/)**
