### ISSUE TITLE
[Bug] npm install does not work, dependencies are a mess

### ISSUE THREAD

**Issue by woodward54** [creativetimofficial/ct-nextjs-material-dashboard-pro#20]
### Version
1.1.0
### Reproduction link
https://www.creative-tim.com/learning-lab/nextjs/quick-start/material-dashboard
### Operating System
macOS
### Device
Macbook
### Browser & Version
Chrome
### Steps to reproduce
Downloaded the project
npm run install:clean
~lots of dependency errors~
### What is expected?
packages should install 
### What is actually happening?
many dependency issues

---
### Solution
n/a
### Additional comments
running node v16.13.1

**Comment by bash4u** [comment]
Having the same issues. Are there any solutions?

**Comment by sajadevo** [comment]
**Hi there**

We've updated the product to v2 and now it has a totally new and fresh design with a reusable, flexible and scalable base structure and all of the issues are fixed on the new update of the product.

**Note: To get the latest updates and supports for the products and other related things to Creative Tim please join our [Discord Community](https://discord.gg/7xzMRsRebr).**

**All the best,
Sajad 
React Developer @ [Creative-Tim.com](http://creative-tim.com/)**
