### ISSUE TITLE
[Bug] Can't get the related Figma files

### ISSUE THREAD

**Issue by Emanuel-Allely** [creativetimofficial/ct-nextjs-material-dashboard-pro#21]
### Version
2.0.0
### Reproduction link
https://www.creative-tim.com/download-psd/nextjs-material-dashboard-pro?designer_technology=figma
### Operating System
Mac
### Device
Macbook
### Browser & Version
Chrome 99.0.4844.74
### Steps to reproduce
Search for NextJS Material Dashboard 2 on the Creative Tim Club
Click on Designer button
Then on Figma
### What is expected?
To get figma files or to go to a shared figma folder...
### What is actually happening?
The page is loading and nothing happens

---

**Comment by Pugialli** [comment]
I'm not from his team but if you open the figma link in a new window the file is downloaded.
