### ISSUE TITLE
[Bug] The engine "node" is incompatible with this module. Expected version "14 || 15 || 16". Got "18.0.0"

### ISSUE THREAD

**Issue by alexandreafc** [creativetimofficial/ct-nextjs-material-dashboard-pro#23]
### Version
2.0.0
### Reproduction link
http://theresnorul.com
### Operating System
Mac OS
### Device
Macbook Pro
### Browser & Version
Chrome
### Steps to reproduce
1. Download de template
2. Extract it
3. Execute yarn install

As my node version is 18 I receive the following message:

[1/5] 🔍  Validating package.json...
error nextjs-material-dashboard-2-pro@1.0.0: The engine "node" is incompatible with this module. Expected version "14 || 15 || 16". Got "18.0.0"
error Found incompatible module.
### What is expected?
To install all dependencies.
### What is actually happening?
Error and stop

---
### Solution
No solution for now, blocked.

**Comment by sajadevo** [comment]
Hey there,

We've updated the product and now it's updated to Next.js 13 and this issue is fixed as well. please update to the latest version (v2.1.0)

Regards,
Sajad
