### ISSUE TITLE
[Bug] Failed to install due to ERESOLVE Found: react@18.0.2 expected react@"^16.8.0 || ^17.0.0"

### ISSUE THREAD

**Issue by somnas** [creativetimofficial/ct-nextjs-material-dashboard-pro#27]
### Version
2.1.0
### Reproduction link
https://demos.creative-tim.com/nextjs-material-dashboard-pro/dashboards/sales
### Operating System
MacOS
### Device
MacBook Pro 
### Browser & Version
Chrome 
### Steps to reproduce
Follow the exact steps as per the product description:

- Unzip project files.
- Open project with whatever terminal and run npm install.
- Watch all the errors
### What is expected?
Project dependancies to be installed.
### What is actually happening?
Npm not able to install dependancies because of broken dependancy tree after updating the project to React 18.

First dependancy to go is @asseinfo/react-kanban@2.2.0. Tried removing it and next one to throw the error is react-images-viewer@1.7.1. Didn't explore further.

---
### Solution
You should work through this and solve the dependancies before releasing. Using --force or --legacy-peer-deps is not an acceptable solution to this even if it would solve the problem temporarily which it doesn’t, neither is having to downgrade to React 17.
### Additional comments
This would maybe be something I could accept to work around if it had been from a YouTube-tutorial or similar, but to buy this product with a company license and run into this and see the same behaviour in pretty much all other React templates from you that I tried instead is unacceptable in my mind.

**Comment by sajadevo** [comment]
This issue is fixed on v2.1.1.
