### ISSUE TITLE
Next.JS Server Component support

### ISSUE THREAD

**Issue by oshrataa** [creativetimofficial/ct-nextjs-material-dashboard-pro#28]
Is is possible to support Server Components features? these were introduced in Next 5 / React 18 
This requires some refactoring of the project, e.g., pages/ ->app/
See https://nextjs.org/docs/app/building-your-application/upgrading/app-router-migration#migrating-from-pages-to-app

**Comment by sajadevo** [comment]
Hey there,

Unfortunately we don't have the plan for this, we'll make other project for appDir but the current products won't be migrated to appDir.

Regards,
Sajad
