### ISSUE TITLE
[Bug] wrong react and next js versions

### ISSUE THREAD

**Issue by myaidev** [creativetimofficial/ct-nextjs-material-dashboard-pro#30]
### Version
2.1.1
### Reproduction link
https://www.creative-tim.com/product/nextjs-material-dashboard-pro
### Operating System
mac
### Device
desktop
### Browser & Version
chrome latest
### Steps to reproduce
In the history change log it was mentioned react and nextjs are upgraded to react 18 and nextjs 13
But when we downloaded the theme for creative tim it is showing react 17 and nextjs 12

### What is expected?
In the history change log it was mentioned react and nextjs are upgraded to react 18 and nextjs 13
### What is actually happening?
But when we downloaded the product it is showing react 17 and nextjs 12

---
### Additional comments
A paid product should maintain minimum quality checks, we have been buzzing the discord and already raised another ticket for this,
No answer for the past 1 week
The Support should tell, when this can be fixed, 
we can not recommend to clients with this kind of behaviour

**Comment by sajadevo** [comment]
Fixed on v2.2.0.
