### ISSUE TITLE
[Bug] WizardSteps file naming case doesn't match Wizard page import

### ISSUE THREAD

**Issue by knthm** [creativetimofficial/ct-nextjs-material-dashboard-pro#7]
### Version
v1.0.0, v1.1.0
### Reproduction link
N/A
### Operating System
Linux
### Device
Any
### Browser & Version
Any
### Steps to reproduce
1. Run `npm run build`
2. Observe node failing to resolve the WizardSteps/Step{n}.js files
### What is expected?
Build should complete without error.
### What is actually happening?
On operating systems with case-sensitive file systems node fails to resolve the incorrectly cased WizardSteps components.

---
### Solution
Rename the WizardSteps components to upper-case:
```diff
From aab9acc7824e73a7e3b099e13164b8e63964a905 Mon Sep 17 00:00:00 2001
From: "Kenneth J. Miller" <ken@miller.ec>
Date: Sun, 31 Jan 2021 12:58:33 +0100
Subject: [PATCH 1/1] BUGFIX: Wizard steps to upper case

---
 components/WizardSteps/{step1.js => Step1.js} | 0
 components/WizardSteps/{step2.js => Step2.js} | 0
 components/WizardSteps/{step3.js => Step3.js} | 0
 3 files changed, 0 insertions(+), 0 deletions(-)
 rename components/WizardSteps/{step1.js => Step1.js} (100%)
 rename components/WizardSteps/{step2.js => Step2.js} (100%)
 rename components/WizardSteps/{step3.js => Step3.js} (100%)

diff --git a/components/WizardSteps/step1.js b/components/WizardSteps/Step1.js
similarity index 100%
rename from components/WizardSteps/step1.js
rename to components/WizardSteps/Step1.js
diff --git a/components/WizardSteps/step2.js b/components/WizardSteps/Step2.js
similarity index 100%
rename from components/WizardSteps/step2.js
rename to components/WizardSteps/Step2.js
diff --git a/components/WizardSteps/step3.js b/components/WizardSteps/Step3.js
similarity index 100%
rename from components/WizardSteps/step3.js
rename to components/WizardSteps/Step3.js
-- 
2.30.1

```

**Comment by sajadevo** [comment]
**Hi there**

We've updated the product to v2 and now it has a totally new and fresh design with a reusable, flexible and scalable base structure and all of the issues are fixed on the new update of the product.

**Note: To get the latest updates and supports for the products and other related things to Creative Tim please join our [Discord Community](https://discord.gg/7xzMRsRebr).**

**All the best,
Sajad 
React Developer @ [Creative-Tim.com](http://creative-tim.com/)**
