### ISSUE TITLE
[Bug] Docker Environment

### ISSUE THREAD

**Issue by daichi1992** [creativetimofficial/ct-nextjs-material-dashboard-pro#9]
### Version
1.1.0
### Reproduction link
http://hoge
### Operating System
mac
### Device
mac
### Browser & Version
chrome
### Steps to reproduce
Just for report.
I have been struggling to make this work on docker environment, and finally I did it.
As you normally use "npm install" + "npm run dev" for docker, sass environment error will arise.
So, I needed to use "npm rebuild node-sass" instead of "npm run dev".

1. "npm install"
2. "npm rebuild node-sass"

### What is expected?
-
### What is actually happening?
-

---
### Solution
1. "npm install"
2. "npm rebuild node-sass"
### Additional comments
I hope this helps someone in the future and am waiting for Docker support.

**Comment by sajadevo** [comment]
**Hi there**

We've updated the product to v2 and now it has a totally new and fresh design with a reusable, flexible and scalable base structure and all of the issues are fixed on the new update of the product.

**Note: To get the latest updates and supports for the products and other related things to Creative Tim please join our [Discord Community](https://discord.gg/7xzMRsRebr).**

**All the best,
Sajad 
React Developer @ [Creative-Tim.com](http://creative-tim.com/)**
